# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
#list(a)只會將array包在一個list中
#a.tolist()則能對多維陣列的每一層作轉換

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
a = np.random.randint(10, size=6) 

print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)

[5 0 1 1 6 5]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
data:  <memory at 0x00000226AEEE4F40>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('data: ', b.data)

[[3 0 1 1]
 [3 7 7 3]
 [2 0 6 0]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
data:  <memory at 0x00000226AEBCA040>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('data: ', c.data)

[[[6 7]
  [5 5]
  [3 5]]

 [[5 2]
  [9 5]
  [8 1]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
data:  <memory at 0x00000226AEA847C0>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size = 6) 

print(a.tolist())
print(list(a))

[8, 8, 9, 0, 4, 5]
[8, 8, 9, 0, 4, 5]


In [7]:
b = np.random.randint(10, size = (3,4)) 

print(b.tolist())
print(list(b))

[[3, 5, 4, 9], [4, 9, 8, 6], [5, 7, 3, 4]]
[array([3, 5, 4, 9]), array([4, 9, 8, 6]), array([5, 7, 3, 4])]


In [8]:
c = np.random.randint(10, size = (2,3,2)) 

print(c.tolist())
print(list(c))

[[[9, 2], [9, 4], [2, 3]], [[5, 3], [9, 7], [5, 9]]]
[array([[9, 2],
       [9, 4],
       [2, 3]]), array([[5, 3],
       [9, 7],
       [5, 9]])]


In [9]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 8, 9, 0, 4, 5]
[[3, 5, 4, 9], [4, 9, 8, 6], [5, 7, 3, 4]]
[[[9, 2], [9, 4], [2, 3]], [[5, 3], [9, 7], [5, 9]]]
